# MAIN CONFIG OF iDrop
block-dropping-directly: false # is on block break, items drop directly to player inventory?
mob-dropping-directly: false # is mob dropping items directly to player inventory?
exp-dropping-directly: false # is experience dropping directly (adding) to player?
